### ISSUE TITLE
Hunter Set page

### ISSUE THREAD

**Issue by Reaver01** [monsterhunteronline/monsterhunteronline.github.io#5]
Hunter Set page needs reviewed and any new info needs added.

**Comment by Zypre** [comment]
The page is pretty good as-is. It's missing a single hunter set (The adrenaline one), but otherwise it appears to be feature-complete

**Comment by Reaver01** [comment]
Ok. then this is our easiest thing.  Just need a picture and the set info.

**Comment by Zypre** [comment]
[Hari added it to faq a while ago](https://cdn.discordapp.com/attachments/122526505606709257/232924707312238593/unknown.png) Don't have an appearance pic on hand right now though.

**Comment by Reaver01** [comment]
Adrenaline set has been added. Closing this.
